name: CI CD pipeline

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master", "develop"]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: 16
      - run: node -v

      - name: Dependencies vulnerabilities
        run: npm audit

      - name: Initialization
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Generate service layer
        run: npm run openapi-generate

      - name: Unit tests
        run: npm run test:unit:ci

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1

      - name: Build
        run: npm run build:ci

#      - name: Save build folder
#        uses: actions/upload-artifact@v3
#        with:
#          name: dist
#          if-no-files-found: error
#          path: dist

  cypress-run-chrome:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome105-ff104-edge
      options: --user 1001
    needs: test-build
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node -v

      - name: Dependencies vulnerabilities
        run: npm audit

      - name: Initialization
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Generate service layer
        run: npm run openapi-generate

      - name: UI Test
        uses: cypress-io/github-action@v5
        with:
#          config: "viewportWidth=375,viewportHeight=667" # for mobile test
          start: npm run dev
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          tag: node-${{ matrix.node }}
          config-file: cypress.config.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: github.event.pull_request.base.ref == 'develop'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: cypress-run-chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate service layer
        run: npm run openapi-generate

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
